from pkg_typo_squatting.generator.utils.generator_functions import parse_package_name

# npm-specific generators
# pypi-specific generators
from pkg_typo_squatting.typo import (
    addDash,
    addition,
    changeOrder,
    closeLetters,
    commonMisspelling,
    doubleHit,
    doubleReplacement,
    formatOutput,
    homoglyph,
    homophones,
    npmPrefix,
    npmScopeSquat,
    npmSeparator,
    npmSubstitution,
    npmSuffix,
    numeralSwap,
    omission,
    pypiPrefix,
    pypiSeparator,
    pypiSubstitution,
    pypiSuffix,
    pypiVersionSuffix,
    removeSeparatedSection,
    repetition,
    replacement,
    runAll,
    singularPluralize,
    stripDash,
    vowelSwap,
)
